[tool.poetry]
name = "analogchess"
version = "0.1.0"
description = ""
authors = ["Ethan Hulinsky", "Zen Tang", "Ben Yarmis"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
